import { extra } from './i18n-extra';
import { extra2 } from './i18n-extra2';
export type Lang = 'az' | 'ru' | 'en';
const baseCopy = {
  az: {
    home: 'Ana səhifə', dashboard: 'İş sahəsi', projects: 'Layihələr', scope: 'İş həcmi', changes: 'Dəyişikliklər',
    milestones: 'Mərhələlər', payments: 'Ödəniş qeydləri', timeline: 'Tarixçə', passport: 'Təmir pasportu',
    newProject: 'Layihə yarat', signIn: 'Daxil ol', signUp: 'Hesab yarat', signOut: 'Çıxış', language: 'Dil',
    tagline: 'Təmir zamanı aydın razılaşma.', hero: 'Təmirin hər addımı aydın və razılaşdırılmış.', lead: 'Ev sahibi və podratçı bütün layihə detallarını bir yerdə razılaşdırır. Dəyişikliklər qeyd olunur, görülən işlər isə foto sübutla təhvil verilir.', start: 'Layihəyə başlayın', learn: 'İş prinsipi',
    trust: 'Birgə iş üçün layihə qeydi', clarity: 'Əvvəlcədən razılaşdırılmış həcm', history: 'Axtarıla bilən layihə tarixçəsi', workflow: 'Sakit koordinasiya. Aydın razılaşma.',
    workflowLead: 'Sözlə deyil, hər iki tərəfin görə biləcəyi qeydlərlə.', stages: ['Həcmi razılaşdırın', 'Dəyişiklikləri qeyd edin', 'Foto ilə təhvil verin'],
    stageDescs: ['Hər otaq üzrə daxil olan və olmayan işləri, material məsuliyyətini və təxminləri yazın.', 'İş gedişində yeni tələb yaranarsa, vaxt və məbləğ təsirini qərardan əvvəl qeyd edin.', 'Mərhələni foto və qeydlərlə təqdim edin. Ev sahibi qəbul edə və ya düzəliş istəyə bilər.'],
    disclaimer: 'Hesab səviyyəsində təsdiq audit qeydi sayılır; bu, hüquqi elektron imza deyil.',
    welcome: 'Yenidən xoş gəlmisiniz', active: 'Aktiv layihələr', pending: 'Sizin diqqətinizi gözləyir', noProjects: 'İlk layihənizdən başlayın', noProjectsText: 'Layihəni yaradın, sonra podratçınızı təhlükəsiz dəvət edin.', createFirst: 'Layihə yarat', loading: 'Məlumat yüklənir', retry: 'Yenidən cəhd et', empty: 'Hələ məlumat yoxdur', save: 'Yadda saxla', cancel: 'Ləğv et', add: 'Əlavə et', submit: 'Göndər', approve: 'Təsdiqlə', accept: 'Qəbul et', accepted: 'Qəbul edildi', requestRevision: 'Düzəliş istə', sent: 'Göndərildi', approved: 'Təsdiqləndi', rejected: 'Rədd edildi', planned: 'Planlaşdırılıb', inProgress: 'İcradadır', pendingApproval: 'Təsdiq gözləyir', resolved: 'Həll edilib', due: 'Vaxtı çatıb', received: 'Qəbul edildi',
    projectName: 'Layihənin adı', city: 'Şəhər', propertyType: 'Əmlak növü', projectType: 'Təmir növü', budget: 'Büdcə (AZN)', startDate: 'Başlama tarixi', completionDate: 'Bitmə tarixi', contractor: 'Podratçı', progress: 'İcra', rooms: 'Otaqlar', included: 'Daxildir', excluded: 'Daxil deyil', approvedBudget: 'Razılaşdırılmış büdcə', totalChanges: 'Təsdiqlənmiş dəyişikliklər', actions: 'Gözləyən addımlar', recent: 'Son fəaliyyət', viewAll: 'Hamısına bax', invite: 'Dəvət et', role: 'İcazə', name: 'Ad', contact: 'E-poçt və ya telefon', makeInvite: 'Dəvət linki yarat', inviteCopied: 'Dəvət linki yaradıldı', addRoom: 'Otaq əlavə et', roomName: 'Otağın adı', itemTitle: 'İşin adı', description: 'Təsvir', inclusion: 'Qərar', materialResponsibility: 'Materialı kim təmin edir?', labor: 'Əmək xərci', materials: 'Material təxmini', warranty: 'Zəmanət (ay)', addScope: 'İş əlavə et', submitScope: 'Həcmi təsdiqə göndər', approvalNote: 'Qeyd (istəyə bağlı)', noChanges: 'Dəyişiklik yoxdur', changeTitle: 'Dəyişikliyin adı', reason: 'Səbəb', laborAmount: 'Əmək', materialAmount: 'Material', delay: 'Əlavə gün', proposeChange: 'Dəyişiklik təklif et', milestoneTitle: 'Mərhələnin adı', milestoneDescription: 'Gözlənilən nəticə', plannedDate: 'Plan tarixi', addMilestone: 'Mərhələ əlavə et', handoverNote: 'Təhvil qeydi', submitHandover: 'Foto sübutla təhvil ver', attachEvidence: 'Foto və ya fayl seçin', evidenceTip: 'Kamera ilə çəkin və ya cihazınızdan fayl seçin. Hər fayl 50 MB-dək.', evidenceReady: 'fayl hazırdır', note: 'Qeyd', revise: 'Düzəliş', requestTitle: 'Düzəliş başlığı', issue: 'Məsələnin təsviri', priority: 'Prioritet', response: 'Cavab', reply: 'Cavab yaz', resolve: 'Həll et', paymentTitle: 'Ödəniş mərhələsi', amount: 'Məbləğ', dueCondition: 'Ödəniş şərti', dueDate: 'Tarix', addPayment: 'Ödəniş qeydi əlavə et', markSent: 'Göndərildiyini qeyd et', confirmReceived: 'Qəbul edildiyini təsdiqlə', manualPayment: 'Yalnız əl ilə aparılan qeyd dəftəridir. Təhvil ödənişləri emal etmir.', passportLead: 'Layihənin bütün vacib razılaşmalarının çap oluna bilən qeydi.', exportPrint: 'Çap et / PDF saxla', status: 'Status', date: 'Tarix', detail: 'Ətraflı', actor: 'İştirakçı', roleOwner: 'Ev sahibi', roleContractor: 'Podratçı', roleViewer: 'Müşahidəçi', propertyApartment: 'Mənzil', propertyHouse: 'Ev', propertyOffice: 'Ofis', propertyCommercial: 'Kommersiya', propertyOther: 'Digər', projectFull: 'Tam təmir', projectPartial: 'Qismən təmir', approveAudit: 'Təsdiq audit qeydi sayılır, hüquqi elektron imza deyil.', signinPrompt: 'Layihə məkanına daxil olun', acceptInvite: 'Dəvəti qəbul et', invitationToken: 'Dəvət tokeni', projectTypeLabel: 'Təmir istiqaməti', created: 'Uğurla yaradıldı', error: 'Sorğu alınmadı. Bir az sonra yenidən cəhd edin.',
    smeta: 'AI Smeta', newBadge: 'Yeni', smetaPromo: 'Smeta, büdcə nəzarəti və sifarişçi təsdiqi bir yerdə.',
  },
  ru: {
    home: 'Главная', dashboard: 'Рабочее пространство', projects: 'Проекты', scope: 'Объём работ', changes: 'Изменения', milestones: 'Этапы', payments: 'Записи оплат', timeline: 'История', passport: 'Паспорт ремонта', newProject: 'Создать проект', signIn: 'Войти', signUp: 'Создать аккаунт', signOut: 'Выйти', language: 'Язык',
    tagline: 'Ясные договорённости на время ремонта.', hero: 'Каждый шаг ремонта —\\nясно и согласовано.', lead: 'Təhvil объединяет владельца и подрядчика в одной записи проекта: согласованный объём до начала работ, изменения и передача с фотоподтверждением.', start: 'Начать проект', learn: 'Как это работает', trust: 'Общее пространство проекта', clarity: 'Согласованный объём заранее', history: 'Полная история проекта', workflow: 'Спокойная координация. Ясные договорённости.', workflowLead: 'Не на словах, а в записях, которые видят обе стороны.', stages: ['Согласовать объём', 'Записать изменения', 'Передать с фото'], stageDescs: ['Укажите работы по каждой комнате, исключения, материалы и оценки.', 'Если появляется новая работа, сначала зафиксируйте влияние на стоимость и сроки.', 'Подрядчик прикладывает фото и заметку. Владелец принимает результат или просит доработку.'], disclaimer: 'Подтверждение в аккаунте — запись аудита, а не юридическая электронная подпись.',
    welcome: 'Добро пожаловать', active: 'Активные проекты', pending: 'Требует вашего внимания', noProjects: 'Начните с первого проекта', noProjectsText: 'Создайте проект, затем безопасно пригласите подрядчика.', createFirst: 'Создать проект', loading: 'Загрузка данных', retry: 'Повторить', empty: 'Пока нет данных', save: 'Сохранить', cancel: 'Отмена', add: 'Добавить', submit: 'Отправить', approve: 'Подтвердить', accept: 'Принять', accepted: 'Принято', requestRevision: 'Запросить доработку', sent: 'Отправлено', approved: 'Подтверждено', rejected: 'Отклонено', planned: 'Запланировано', inProgress: 'В работе', pendingApproval: 'Ожидает подтверждения', resolved: 'Решено', due: 'К оплате', received: 'Получено',
    projectName: 'Название проекта', city: 'Город', propertyType: 'Тип объекта', projectType: 'Тип ремонта', budget: 'Бюджет (AZN)', startDate: 'Дата начала', completionDate: 'Дата завершения', contractor: 'Подрядчик', progress: 'Готовность', rooms: 'Комнаты', included: 'Включено', excluded: 'Исключено', approvedBudget: 'Согласованный бюджет', totalChanges: 'Подтверждённые изменения', actions: 'Ожидаемые действия', recent: 'Недавняя активность', viewAll: 'Посмотреть всё', invite: 'Пригласить', role: 'Роль', name: 'Имя', contact: 'Эл. почта или телефон', makeInvite: 'Создать ссылку-приглашение', inviteCopied: 'Ссылка создана', addRoom: 'Добавить комнату', roomName: 'Название комнаты', itemTitle: 'Название работы', description: 'Описание', inclusion: 'Решение', materialResponsibility: 'Кто предоставляет материалы?', labor: 'Работа', materials: 'Материалы', warranty: 'Гарантия (мес.)', addScope: 'Добавить работу', submitScope: 'Отправить объём на подтверждение', approvalNote: 'Комментарий (необязательно)', noChanges: 'Изменений нет', changeTitle: 'Название изменения', reason: 'Причина', laborAmount: 'Работа', materialAmount: 'Материалы', delay: 'Доп. дни', proposeChange: 'Предложить изменение', milestoneTitle: 'Название этапа', milestoneDescription: 'Ожидаемый результат', plannedDate: 'Плановая дата', addMilestone: 'Добавить этап', handoverNote: 'Комментарий к передаче', submitHandover: 'Передать с фотоподтверждением', attachEvidence: 'Выбрать фото или файл', evidenceTip: 'Снимите камерой или выберите файл. До 50 МБ каждый.', evidenceReady: 'файл готов', note: 'Комментарий', revise: 'Доработка', requestTitle: 'Тема доработки', issue: 'Описание проблемы', priority: 'Приоритет', response: 'Ответ', reply: 'Ответить', resolve: 'Решить', paymentTitle: 'Этап оплаты', amount: 'Сумма', dueCondition: 'Условие оплаты', dueDate: 'Дата', addPayment: 'Добавить запись оплаты', markSent: 'Отметить отправку', confirmReceived: 'Подтвердить получение', manualPayment: 'Только ручной журнал. Təhvil не обрабатывает платежи.', passportLead: 'Печатная запись всех важных договорённостей проекта.', exportPrint: 'Печать / сохранить PDF', status: 'Статус', date: 'Дата', detail: 'Детали', actor: 'Участник', roleOwner: 'Владелец', roleContractor: 'Подрядчик', roleViewer: 'Наблюдатель', propertyApartment: 'Квартира', propertyHouse: 'Дом', propertyOffice: 'Офис', propertyCommercial: 'Коммерческое', propertyOther: 'Другое', projectFull: 'Полный ремонт', projectPartial: 'Частичный ремонт', approveAudit: 'Подтверждение — запись аудита, а не юридическая электронная подпись.', signinPrompt: 'Войдите в проектное пространство', acceptInvite: 'Принять приглашение', invitationToken: 'Токен приглашения', projectTypeLabel: 'Направление ремонта', created: 'Успешно создано', error: 'Не удалось выполнить запрос. Попробуйте ещё раз.',
    smeta: 'AI Smeta', newBadge: 'Новое', smetaPromo: 'Смета, контроль бюджета и согласование с заказчиком в одном месте.',
  },
  en: {
    home: 'Home', dashboard: 'Workspace', projects: 'Projects', scope: 'Scope', changes: 'Changes', milestones: 'Milestones', payments: 'Payment notes', timeline: 'Timeline', passport: 'Renovation passport', newProject: 'New project', signIn: 'Sign in', signUp: 'Create account', signOut: 'Sign out', language: 'Language',
    tagline: 'Clear agreements for the work ahead.', hero: 'Every step of renovation,\\nclear and agreed.', lead: 'Təhvil brings homeowners and contractors into one shared project record: agreed scope before work begins, documented changes, and evidence-led handovers.', start: 'Start a project', learn: 'How it works', trust: 'One shared project record', clarity: 'Scope agreed before work', history: 'A complete project history', workflow: 'Calm coordination. Clear agreements.', workflowLead: 'Not just spoken promises — a record both people can see.', stages: ['Agree the scope', 'Record every change', 'Hand over with evidence'], stageDescs: ['List included and excluded work by room, along with materials and estimates.', 'When something changes, capture the cost and schedule impact before deciding.', 'Submit each milestone with photos and notes. Accept it or request a revision.'], disclaimer: 'Account-level approval is an audit record, not a legal electronic signature.',
    welcome: 'Welcome back', active: 'Active projects', pending: 'Needs your attention', noProjects: 'Start with your first project', noProjectsText: 'Create a project, then invite your contractor securely.', createFirst: 'Create a project', loading: 'Loading your workspace', retry: 'Try again', empty: 'Nothing here yet', save: 'Save', cancel: 'Cancel', add: 'Add', submit: 'Submit', approve: 'Approve', accept: 'Accept', accepted: 'Accepted', requestRevision: 'Request revision', sent: 'Submitted', approved: 'Approved', rejected: 'Rejected', planned: 'Planned', inProgress: 'In progress', pendingApproval: 'Awaiting approval', resolved: 'Resolved', due: 'Due', received: 'Received',
    projectName: 'Project name', city: 'City', propertyType: 'Property type', projectType: 'Project type', budget: 'Budget (AZN)', startDate: 'Planned start', completionDate: 'Planned completion', contractor: 'Contractor', progress: 'Progress', rooms: 'Rooms', included: 'Included', excluded: 'Excluded', approvedBudget: 'Agreed budget', totalChanges: 'Approved changes', actions: 'Next actions', recent: 'Recent activity', viewAll: 'View all', invite: 'Invite', role: 'Role', name: 'Name', contact: 'Email or phone', makeInvite: 'Create invite link', inviteCopied: 'Invite link created', addRoom: 'Add a room', roomName: 'Room name', itemTitle: 'Work item', description: 'Description', inclusion: 'Decision', materialResponsibility: 'Who supplies materials?', labor: 'Labor estimate', materials: 'Material estimate', warranty: 'Warranty (months)', addScope: 'Add work item', submitScope: 'Submit scope for approval', approvalNote: 'Comment (optional)', noChanges: 'No changes yet', changeTitle: 'Change title', reason: 'Reason', laborAmount: 'Labor', materialAmount: 'Materials', delay: 'Schedule impact (days)', proposeChange: 'Propose a change', milestoneTitle: 'Milestone title', milestoneDescription: 'Expected outcome', plannedDate: 'Planned date', addMilestone: 'Add milestone', handoverNote: 'Handover note', submitHandover: 'Submit handover with evidence', attachEvidence: 'Choose photos or files', evidenceTip: 'Take a photo or choose a file. Up to 50 MB each.', evidenceReady: 'file ready', note: 'Note', revise: 'Revision', requestTitle: 'Revision title', issue: 'Describe the issue', priority: 'Priority', response: 'Response', reply: 'Reply', resolve: 'Resolve', paymentTitle: 'Payment milestone', amount: 'Amount', dueCondition: 'Due condition', dueDate: 'Date', addPayment: 'Add payment note', markSent: 'Mark sent', confirmReceived: 'Confirm received', manualPayment: 'Manual tracking only. Təhvil does not process payments.', passportLead: 'A printable record of the project’s important agreements.', exportPrint: 'Print / save PDF', status: 'Status', date: 'Date', detail: 'Detail', actor: 'Participant', roleOwner: 'Homeowner', roleContractor: 'Contractor', roleViewer: 'Observer', propertyApartment: 'Apartment', propertyHouse: 'House', propertyOffice: 'Office', propertyCommercial: 'Commercial', propertyOther: 'Other', projectFull: 'Full renovation', projectPartial: 'Partial renovation', approveAudit: 'Approval is an audit record, not a legal electronic signature.', signinPrompt: 'Sign in to your project workspace', acceptInvite: 'Accept invitation', invitationToken: 'Invitation token', created: 'Created successfully', error: 'The request did not complete. Please try again.',
    smeta: 'AI Smeta', newBadge: 'New', smetaPromo: 'Estimates, budget control and client approval in one place.',
  },
} as const;

export const copy = { az: { ...baseCopy.az, ...extra.az, ...extra2.az }, ru: { ...baseCopy.ru, ...extra.ru, ...extra2.ru }, en: { ...baseCopy.en, ...extra.en, ...extra2.en } } as const;
export type TKey = keyof typeof copy.en;
