import { useState, type FormEvent } from 'react';
import { Check, FilePlus2, MessageSquareText, Plus, X } from 'lucide-react';
import type { ChangeOrder, Room } from '@workspace/api-client-react';
import { Button, Field, PageHeading, QuerySection, Status, date, money, type T } from '@/components/kit';

export function ChangesPage(p: any) {
  const { t, changes, rooms, id, createChange, decideChange, refreshCore, notify, lang, me, canWrite, scopeApproved } = p as Record<string, any> & { t: T };
  const [open, setOpen] = useState(false);
  const [comments, setComments] = useState<Record<string, string>>({});
  const [form, setForm] = useState({ title: '', reason: '', description: '', roomId: '', laborAmount: '0', materialAmount: '0', scheduleImpactDays: '0', newCompletionDate: '' });
  const canPropose = canWrite && scopeApproved;
  const submit = (e: FormEvent) => { e.preventDefault(); createChange.mutate({ projectId: id, data: { ...form, roomId: form.roomId || null, description: form.description || null, laborAmount: Number(form.laborAmount), materialAmount: Number(form.materialAmount), scheduleImpactDays: Number(form.scheduleImpactDays), newCompletionDate: form.newCompletionDate || null } }, { onSuccess: () => { setOpen(false); setForm({ ...form, title: '', reason: '', description: '' }); notify(t('sent')); refreshCore(); } }); };
  const decide = (c: ChangeOrder, decision: 'approve' | 'clarify' | 'reject', msg: string) => decideChange.mutate({ changeOrderId: c.id, data: { decision, comment: comments[c.id]?.trim() || null } }, { onSuccess: () => { refreshCore(); notify(msg); } });
  const list: ChangeOrder[] = changes.data || [];
  return <><PageHeading eyebrow={t('eyChange')} title={t('changes')} description={t('stages')[1]} action={canPropose ? <Button onClick={() => setOpen(!open)} testId="button-propose-change"><Plus size={16} />{t('proposeChange')}</Button> : undefined} />
    {!scopeApproved && <div className="notice manual-notice">{t('changesLocked')}</div>}
    {open && canPropose && <form className="surface form-card compact-form" onSubmit={submit}><div className="field-grid"><Field label={t('changeTitle')} name="change-title" required value={form.title} onChange={v => setForm({ ...form, title: v })} /><Field label={t('rooms')} name="change-room"><select value={form.roomId} onChange={e => setForm({ ...form, roomId: e.target.value })}><option value="">—</option>{(rooms.data || []).map((r: Room) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></Field></div><Field label={t('reason')} name="change-reason" required><textarea required value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></Field><Field label={t('description')} name="change-description"><textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field><div className="field-grid three"><Field label={t('laborAmount')} name="change-labor" type="number" min="0" value={form.laborAmount} onChange={v => setForm({ ...form, laborAmount: v })} /><Field label={t('materialAmount')} name="change-material" type="number" min="0" value={form.materialAmount} onChange={v => setForm({ ...form, materialAmount: v })} /><Field label={t('delay')} name="change-days" type="number" min="0" value={form.scheduleImpactDays} onChange={v => setForm({ ...form, scheduleImpactDays: v })} /></div><div className="inline-actions"><Button variant="secondary" onClick={() => setOpen(false)}>{t('cancel')}</Button><Button type="submit" disabled={createChange.isPending}>{t('submit')}</Button></div></form>}
    <QuerySection q={changes} t={t}><div className="change-list">{list.map(c => {
      const decidable = canWrite && ['submitted', 'needs_clarification'].includes(c.status);
      const own = (c as any).createdBy === me;
      return <article className="change-card surface" key={c.id} data-testid={`card-change-${c.id}`}><div className="change-number">CO-{String(c.number).padStart(3, '0')}</div><div className="change-main"><div className="change-card-title"><h3>{c.title}</h3><Status value={c.status} t={t} /></div><p>{c.reason}</p><div className="change-meta"><span>{c.roomName || t('rooms')}</span><span>{date(c.createdAt, lang)}</span><span>{c.scheduleImpactDays} {t('days')}</span></div>{c.decisionComment && <div className="decision-note"><MessageSquareText size={14} />{c.decisionComment}</div>}{decidable && own && <small className="revision-date">{t('ownChange')}</small>}</div>
        <div className="change-amount"><small>{t('amount')}</small><strong>{money(c.totalAmount)} <small>AZN</small></strong>
          {decidable && !own && <div className="decision-box"><input className="decision-input" placeholder={t('decisionComment')} value={comments[c.id] || ''} onChange={e => setComments({ ...comments, [c.id]: e.target.value })} /><div className="mini-actions"><Button onClick={() => decide(c, 'approve', t('approved'))} disabled={decideChange.isPending}><Check size={13} />{t('approve')}</Button><Button variant="secondary" onClick={() => decide(c, 'clarify', t('sent'))} disabled={decideChange.isPending}><MessageSquareText size={13} />{t('clarify')}</Button><Button variant="danger" onClick={() => decide(c, 'reject', t('rejected'))} disabled={decideChange.isPending}><X size={13} />{t('reject')}</Button></div></div>}
        </div></article>;
    })}{!list.length && <div className="empty-projects compact-empty"><div className="empty-illustration"><FilePlus2 size={32} /></div><h2 className="font-display">{t('noChanges')}</h2><p>{t('stages')[1]}</p>{canPropose && <Button onClick={() => setOpen(true)}><Plus size={16} />{t('proposeChange')}</Button>}</div>}</div></QuerySection></>;
}
